### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [SohtR/toxinHotelUiKit#10]
Добавить команду для клонирования репозитория

**Comment by SohtR** [comment]
В Readme написано: 
"To clone repository to your local storage: git clone https://github.com/SohtR/toxinHotelUiKit.git"
этого недостаточно?

**Comment by GoodDayTodayOkey** [comment]
Не обратил внимание, оформи плиз команду, тоже вставкой кода, чтобы выделялось. Как выделишь, это ишью можно закрывать.
