### ISSUE TITLE
устранить неполадки сборки

### ISSUE THREAD

**Issue by Sergio-Ka** [SohtR/toxinHotelUiKit#2]
Каждый проверяющий (а в последствии и работающий с твоим репозиторием при командной разработке) должен клонировать репозиторий, установить зависимости с помощью npm i и все скрипты должны работать. Сейчас при запуске сервера выдает следующую картину:
![image](https://user-images.githubusercontent.com/33621369/61116222-34515e00-a4be-11e9-904f-b85bb32bcb53.png)
при сборке dev тоже выдает ошибки. На сколько я понимаю что-то со шрифтами.

**Comment by SohtR** [comment]
К сожалению, не получилось воспроизвести ошибку. Клонировал по инструкции из README в 2 разные папки, но безрезультатно. Всё работало

**Comment by Sergio-Ka** [comment]
Проект не собирается. JS регистрозависимый, он пытается найти файл textfield.pug, но там такого нет, есть только textField.pug. Вообще надо с нуля проверять проекты на предмет скачивания и разворачивания на локальном компе, это есть в стандартах.
![image](https://user-images.githubusercontent.com/33621369/62999416-8b20cd80-be98-11e9-9fe8-0965548125f4.png)
![image](https://user-images.githubusercontent.com/33621369/62999459-b60b2180-be98-11e9-90fa-efbf33c9c7a2.png)
