### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Sergio-Ka** [SohtR/toxinHotelUiKit#6]
1. В проекте полностью соблюдать требование методологии БЭМ. Исключение  - позиционирование блоков, вместо миксов их нужно помещать в обертки, которые являются элементами родительского блока по БЭМ. И уже на эти обертки (элементы) вешать позиционирование. Миксы не допустимы.
2. Блоки по БЭМ должны быть реализованы миксинами pug. Параметры блоков должны передаваться объектами js - в корневом блоке задаваться все параметры, внутри распределятся по более мелким блокам. То есть у проекта должна быть древовидная структура. Это требование компонентности верстки подобно подходу, применяемому в react.

**Comment by Sergio-Ka** [comment]
Вообще не понятно, почему например btnFill и btnLong оформлены двумя разными блоками? Если это кнопка, то как правило разница в видах решается с помощью модификаторов, что сокращает код и позволяет переиспользовать то, что можно. Это краеуголный камень методологии БЭМ. И это не только касательно кнопок. Впрочем тут я пока проект не соберу до конца его понять не могу, потому утверждать категорично не буду. Проект даже как-то странно на gitHub Pages выглядит, похоже над ним надо еще поработать. Во всяком случае я мало чего похожего вижу с макетом.

**Comment by Sergio-Ka** [comment]
По БЭМ нельзя использовать селекторы тегов, кроме body и html в корне.
![image](https://user-images.githubusercontent.com/33621369/63587854-39322300-c5cf-11e9-8209-2a5a839f5ac4.png)

**Comment by Sergio-Ka** [comment]
Селекторы тегов все еще используются в проекте.

**Comment by Sergio-Ka** [comment]
1. Еще раз. Миксы в отличии от оригинального БЭМ у нас по стандартам внутренним не допустимы. Вот эта запись td.roomDetail__priceTable-column.roomDetail__rightCol является миксом (это только как пример, у тебя везде используются миксы). Это не допустимо. Основные задачи, которые решаются миксами в оригинальной методологии как правило - это позиционирование блока, но это у нас решается как я говорил посредством обертки в которую помещается блок (обертка здесь - это элемент по БЭМ родительского блока по БЭМ для этого блока для которого делается обертка). И на обертку уже вешается позиционирование. Если ты пытаешься использовать микс для изменения вида блока, то стандартная практика здесь - это использовать модификаторы. Используя миксы в этом случае ты увеличиваешь зацепление и затрудняешь переиспользование блоков. А если ты миксуешь элементы одного блока как здесь то тоже плохо, так как ты не правильно используешь методологию.
2.     p.roomDetail__price 9 990₽ в сутки
    .flex-wrapper
        include ../two-input-range/two-input-range.pug
    .dropdownGuest
        h3.roomDetail__header гости
        include ../dropdown-guest-repeat/dropdown-guest-repeat.pug
    table.roomDetail__priceTable 
В этом месте ты используешь для одного блока картинки из другого блока - таким образом добавляются зависимости, увеличивается зацепление (coupling), как следствие затрудняется переиспользование блоков на проектах, потому что одни блоки знают о кусках реализации других блоков (а картинка это часть реализации блока). Создай папку в src назови ее images и все общие для разных блоков картинки размещай там. Если картинка используется только для одного блока, то ее можно размещать внутри блока в папке images.

**Comment by Sergio-Ka** [comment]
Пункты 3, 4, 5 не выполнены. Вот пример:
```
mixin card-login(data)
    .login-account
        h1.login-account__header= data.header
        +textfield(data.emailField.id, data.emailField.placeholder, data.emailField.type)
        +textfield(data.passField.id, data.passField.placeholder, data.passField.type)
        +button(data.btnLongStyle, data.btnLongContent)
        .flex-wrapper
            p.have-account Нет аккаунта на Toxin?
            +button(data.btnBorderStyle, data.btnBorderContent)
```
и далее по коду.

**Comment by SohtR** [comment]
Извини, я не понял по этому примеру, можно чуть подробнее, пожалуйста?

**Comment by Sergio-Ka** [comment]
Пункты 3, 4, 5 из моего поста еще выше. Что конкретно там не понятно? Изложено достаточно подробно на мой взгляд. У тебя БЭМ блок (считай компонент) всегда должен быть миксином. Так как верстка компонентная, то из этих блоков (компонент) и складывается все приложение (вся верстка). Здесь в приведенном фрагменте у тебя есть миксин card-login, в нем должны быть только его элементы или вызовы других миксинов, но у тебя здесь есть БЭМ блоки .flex-wrapper и .have-account (что это именно блоки я делаю вывод исходя из методологии БЭМ и вида названий). Но как я уже сказал к блокам требования особые - они оформляются миксинами и лежат в отдельных папках вместе со своими реализациями.

**Comment by Sergio-Ka** [comment]
Вот еще пример:
```
.room-detail{
  height: 31.9375rem;
  width: 380px;
  padding: 40px 30px 30px 30px;
  background: #fff;
  border: 1px solid rgba(0, 0, 0, 0.12);
  box-sizing: border-box;
  box-shadow: 0px 0px 25px rgba(0, 0, 0, 0.2);
  border-radius: 4px;
  z-index: 1;
  
  .button_border{
    margin: 2px 0 0 36px;
    width: 96px;
    height: 40px;
    box-sizing: border-box;
    display: inline-block;
    line-height: 26px;
  }
  .have-account{
    font-size: 14px;
    line-height: 18px;
    color: #000;
  }
```
В папке блока лежать всегда только его реализации. В данном случае стили. А у тебя блок блок card-room-detail (что уже не верно ибо название миксина, название pug файла и название папки блока должны быть одинаковыми), и в нем лежат почему-то стили для .button_border (это кусок реализации компонента button) и .have-account (это вообще отдельный компонент.

Вообще из всех этих замечаний я делаю вывод что методология БЭМ не понятна от слова совсем и смысл компонентности и что это такое вообще так же не ясно. Тут вариант пойти поизучать теорию еще. Если что-то совсем не понятно, поспрашивать в чате у других людей, проходящих обучение паралельно. Можно поспрашивать у меня, но только конкретными вопросами, потому что вопрос общего вида "я ничего не понял", это не вопрос - это крик души.

**Comment by Sergio-Ka** [comment]
Вообще на самом деле вопрос с БЭМом важный самый, базовый и основополагающий. Сейчас вся верстка выглядит как каша и очень сложно воспринимать код и выискивать остальные замечания. Поэтому до тех пор пока код не будет четко разбит на компоненты и компоненты не станут именно компонентами (то есть независимыми частями кода, реализации которых не размазаны по всему проекту и которые можно легко переиспользовать) смысла дальнейших движений по проверке не вижу.
